/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CognatesIndexRouteImport } from './routes/cognates/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as ArabicWithMuftiSaimIndexRouteImport } from './routes/arabic-with-mufti-saim/index'
import { Route as ChallengesVocabularyIndexRouteImport } from './routes/challenges/vocabulary/index'
import { Route as ArabicWithMuftiSaimLectureLectureIdRouteImport } from './routes/arabic-with-mufti-saim/lecture.$lectureId'
import { Route as ApiPublishSplatRouteImport } from './routes/api/publish/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ChallengesGrammarYesNoQuestionsIndexRouteImport } from './routes/challenges/grammar/yes-no-questions/index'
import { Route as ChallengesGrammarPrepositionsIndexRouteImport } from './routes/challenges/grammar/prepositions/index'
import { Route as ChallengesGrammarMubtadaKhabarIndexRouteImport } from './routes/challenges/grammar/mubtada-khabar/index'
import { Route as ChallengesGrammarMasculineFeminineIndexRouteImport } from './routes/challenges/grammar/masculine-feminine/index'
import { Route as ChallengesGrammarIsmIshaaraNearIndexRouteImport } from './routes/challenges/grammar/ism-ishaara-near/index'
import { Route as ChallengesGrammarIsmIshaaraFarIndexRouteImport } from './routes/challenges/grammar/ism-ishaara-far/index'
import { Route as ChallengesGrammarInterrogativesManMaaIndexRouteImport } from './routes/challenges/grammar/interrogatives-man-maa/index'
import { Route as ChallengesGrammarIndependentPronounsIndexRouteImport } from './routes/challenges/grammar/independent-pronouns/index'
import { Route as ChallengesGrammarIdafahIndexRouteImport } from './routes/challenges/grammar/idafah/index'
import { Route as ChallengesGrammarDefinitenessTanwinIndexRouteImport } from './routes/challenges/grammar/definiteness-tanwin/index'
import { Route as ChallengesGrammarColorsIndexRouteImport } from './routes/challenges/grammar/colors/index'
import { Route as ChallengesGrammarCaseSystemOverviewIndexRouteImport } from './routes/challenges/grammar/case-system-overview/index'
import { Route as ChallengesGrammarAttachedPronounsIndexRouteImport } from './routes/challenges/grammar/attached-pronouns/index'
import { Route as ChallengesGrammarAdjectivesAgreementIndexRouteImport } from './routes/challenges/grammar/adjectives-agreement/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CognatesIndexRoute = CognatesIndexRouteImport.update({
  id: '/cognates/',
  path: '/cognates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArabicWithMuftiSaimIndexRoute =
  ArabicWithMuftiSaimIndexRouteImport.update({
    id: '/arabic-with-mufti-saim/',
    path: '/arabic-with-mufti-saim/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesVocabularyIndexRoute =
  ChallengesVocabularyIndexRouteImport.update({
    id: '/challenges/vocabulary/',
    path: '/challenges/vocabulary/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArabicWithMuftiSaimLectureLectureIdRoute =
  ArabicWithMuftiSaimLectureLectureIdRouteImport.update({
    id: '/arabic-with-mufti-saim/lecture/$lectureId',
    path: '/arabic-with-mufti-saim/lecture/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublishSplatRoute = ApiPublishSplatRouteImport.update({
  id: '/api/publish/$',
  path: '/api/publish/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesGrammarYesNoQuestionsIndexRoute =
  ChallengesGrammarYesNoQuestionsIndexRouteImport.update({
    id: '/challenges/grammar/yes-no-questions/',
    path: '/challenges/grammar/yes-no-questions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarPrepositionsIndexRoute =
  ChallengesGrammarPrepositionsIndexRouteImport.update({
    id: '/challenges/grammar/prepositions/',
    path: '/challenges/grammar/prepositions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarMubtadaKhabarIndexRoute =
  ChallengesGrammarMubtadaKhabarIndexRouteImport.update({
    id: '/challenges/grammar/mubtada-khabar/',
    path: '/challenges/grammar/mubtada-khabar/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarMasculineFeminineIndexRoute =
  ChallengesGrammarMasculineFeminineIndexRouteImport.update({
    id: '/challenges/grammar/masculine-feminine/',
    path: '/challenges/grammar/masculine-feminine/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarIsmIshaaraNearIndexRoute =
  ChallengesGrammarIsmIshaaraNearIndexRouteImport.update({
    id: '/challenges/grammar/ism-ishaara-near/',
    path: '/challenges/grammar/ism-ishaara-near/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarIsmIshaaraFarIndexRoute =
  ChallengesGrammarIsmIshaaraFarIndexRouteImport.update({
    id: '/challenges/grammar/ism-ishaara-far/',
    path: '/challenges/grammar/ism-ishaara-far/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarInterrogativesManMaaIndexRoute =
  ChallengesGrammarInterrogativesManMaaIndexRouteImport.update({
    id: '/challenges/grammar/interrogatives-man-maa/',
    path: '/challenges/grammar/interrogatives-man-maa/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarIndependentPronounsIndexRoute =
  ChallengesGrammarIndependentPronounsIndexRouteImport.update({
    id: '/challenges/grammar/independent-pronouns/',
    path: '/challenges/grammar/independent-pronouns/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarIdafahIndexRoute =
  ChallengesGrammarIdafahIndexRouteImport.update({
    id: '/challenges/grammar/idafah/',
    path: '/challenges/grammar/idafah/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarDefinitenessTanwinIndexRoute =
  ChallengesGrammarDefinitenessTanwinIndexRouteImport.update({
    id: '/challenges/grammar/definiteness-tanwin/',
    path: '/challenges/grammar/definiteness-tanwin/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarColorsIndexRoute =
  ChallengesGrammarColorsIndexRouteImport.update({
    id: '/challenges/grammar/colors/',
    path: '/challenges/grammar/colors/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarCaseSystemOverviewIndexRoute =
  ChallengesGrammarCaseSystemOverviewIndexRouteImport.update({
    id: '/challenges/grammar/case-system-overview/',
    path: '/challenges/grammar/case-system-overview/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarAttachedPronounsIndexRoute =
  ChallengesGrammarAttachedPronounsIndexRouteImport.update({
    id: '/challenges/grammar/attached-pronouns/',
    path: '/challenges/grammar/attached-pronouns/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesGrammarAdjectivesAgreementIndexRoute =
  ChallengesGrammarAdjectivesAgreementIndexRouteImport.update({
    id: '/challenges/grammar/adjectives-agreement/',
    path: '/challenges/grammar/adjectives-agreement/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arabic-with-mufti-saim/': typeof ArabicWithMuftiSaimIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/cognates/': typeof CognatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/publish/$': typeof ApiPublishSplatRoute
  '/arabic-with-mufti-saim/lecture/$lectureId': typeof ArabicWithMuftiSaimLectureLectureIdRoute
  '/challenges/vocabulary/': typeof ChallengesVocabularyIndexRoute
  '/challenges/grammar/adjectives-agreement/': typeof ChallengesGrammarAdjectivesAgreementIndexRoute
  '/challenges/grammar/attached-pronouns/': typeof ChallengesGrammarAttachedPronounsIndexRoute
  '/challenges/grammar/case-system-overview/': typeof ChallengesGrammarCaseSystemOverviewIndexRoute
  '/challenges/grammar/colors/': typeof ChallengesGrammarColorsIndexRoute
  '/challenges/grammar/definiteness-tanwin/': typeof ChallengesGrammarDefinitenessTanwinIndexRoute
  '/challenges/grammar/idafah/': typeof ChallengesGrammarIdafahIndexRoute
  '/challenges/grammar/independent-pronouns/': typeof ChallengesGrammarIndependentPronounsIndexRoute
  '/challenges/grammar/interrogatives-man-maa/': typeof ChallengesGrammarInterrogativesManMaaIndexRoute
  '/challenges/grammar/ism-ishaara-far/': typeof ChallengesGrammarIsmIshaaraFarIndexRoute
  '/challenges/grammar/ism-ishaara-near/': typeof ChallengesGrammarIsmIshaaraNearIndexRoute
  '/challenges/grammar/masculine-feminine/': typeof ChallengesGrammarMasculineFeminineIndexRoute
  '/challenges/grammar/mubtada-khabar/': typeof ChallengesGrammarMubtadaKhabarIndexRoute
  '/challenges/grammar/prepositions/': typeof ChallengesGrammarPrepositionsIndexRoute
  '/challenges/grammar/yes-no-questions/': typeof ChallengesGrammarYesNoQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arabic-with-mufti-saim': typeof ArabicWithMuftiSaimIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/cognates': typeof CognatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/publish/$': typeof ApiPublishSplatRoute
  '/arabic-with-mufti-saim/lecture/$lectureId': typeof ArabicWithMuftiSaimLectureLectureIdRoute
  '/challenges/vocabulary': typeof ChallengesVocabularyIndexRoute
  '/challenges/grammar/adjectives-agreement': typeof ChallengesGrammarAdjectivesAgreementIndexRoute
  '/challenges/grammar/attached-pronouns': typeof ChallengesGrammarAttachedPronounsIndexRoute
  '/challenges/grammar/case-system-overview': typeof ChallengesGrammarCaseSystemOverviewIndexRoute
  '/challenges/grammar/colors': typeof ChallengesGrammarColorsIndexRoute
  '/challenges/grammar/definiteness-tanwin': typeof ChallengesGrammarDefinitenessTanwinIndexRoute
  '/challenges/grammar/idafah': typeof ChallengesGrammarIdafahIndexRoute
  '/challenges/grammar/independent-pronouns': typeof ChallengesGrammarIndependentPronounsIndexRoute
  '/challenges/grammar/interrogatives-man-maa': typeof ChallengesGrammarInterrogativesManMaaIndexRoute
  '/challenges/grammar/ism-ishaara-far': typeof ChallengesGrammarIsmIshaaraFarIndexRoute
  '/challenges/grammar/ism-ishaara-near': typeof ChallengesGrammarIsmIshaaraNearIndexRoute
  '/challenges/grammar/masculine-feminine': typeof ChallengesGrammarMasculineFeminineIndexRoute
  '/challenges/grammar/mubtada-khabar': typeof ChallengesGrammarMubtadaKhabarIndexRoute
  '/challenges/grammar/prepositions': typeof ChallengesGrammarPrepositionsIndexRoute
  '/challenges/grammar/yes-no-questions': typeof ChallengesGrammarYesNoQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arabic-with-mufti-saim/': typeof ArabicWithMuftiSaimIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/cognates/': typeof CognatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/publish/$': typeof ApiPublishSplatRoute
  '/arabic-with-mufti-saim/lecture/$lectureId': typeof ArabicWithMuftiSaimLectureLectureIdRoute
  '/challenges/vocabulary/': typeof ChallengesVocabularyIndexRoute
  '/challenges/grammar/adjectives-agreement/': typeof ChallengesGrammarAdjectivesAgreementIndexRoute
  '/challenges/grammar/attached-pronouns/': typeof ChallengesGrammarAttachedPronounsIndexRoute
  '/challenges/grammar/case-system-overview/': typeof ChallengesGrammarCaseSystemOverviewIndexRoute
  '/challenges/grammar/colors/': typeof ChallengesGrammarColorsIndexRoute
  '/challenges/grammar/definiteness-tanwin/': typeof ChallengesGrammarDefinitenessTanwinIndexRoute
  '/challenges/grammar/idafah/': typeof ChallengesGrammarIdafahIndexRoute
  '/challenges/grammar/independent-pronouns/': typeof ChallengesGrammarIndependentPronounsIndexRoute
  '/challenges/grammar/interrogatives-man-maa/': typeof ChallengesGrammarInterrogativesManMaaIndexRoute
  '/challenges/grammar/ism-ishaara-far/': typeof ChallengesGrammarIsmIshaaraFarIndexRoute
  '/challenges/grammar/ism-ishaara-near/': typeof ChallengesGrammarIsmIshaaraNearIndexRoute
  '/challenges/grammar/masculine-feminine/': typeof ChallengesGrammarMasculineFeminineIndexRoute
  '/challenges/grammar/mubtada-khabar/': typeof ChallengesGrammarMubtadaKhabarIndexRoute
  '/challenges/grammar/prepositions/': typeof ChallengesGrammarPrepositionsIndexRoute
  '/challenges/grammar/yes-no-questions/': typeof ChallengesGrammarYesNoQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arabic-with-mufti-saim/'
    | '/challenges/'
    | '/cognates/'
    | '/api/auth/$'
    | '/api/publish/$'
    | '/arabic-with-mufti-saim/lecture/$lectureId'
    | '/challenges/vocabulary/'
    | '/challenges/grammar/adjectives-agreement/'
    | '/challenges/grammar/attached-pronouns/'
    | '/challenges/grammar/case-system-overview/'
    | '/challenges/grammar/colors/'
    | '/challenges/grammar/definiteness-tanwin/'
    | '/challenges/grammar/idafah/'
    | '/challenges/grammar/independent-pronouns/'
    | '/challenges/grammar/interrogatives-man-maa/'
    | '/challenges/grammar/ism-ishaara-far/'
    | '/challenges/grammar/ism-ishaara-near/'
    | '/challenges/grammar/masculine-feminine/'
    | '/challenges/grammar/mubtada-khabar/'
    | '/challenges/grammar/prepositions/'
    | '/challenges/grammar/yes-no-questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arabic-with-mufti-saim'
    | '/challenges'
    | '/cognates'
    | '/api/auth/$'
    | '/api/publish/$'
    | '/arabic-with-mufti-saim/lecture/$lectureId'
    | '/challenges/vocabulary'
    | '/challenges/grammar/adjectives-agreement'
    | '/challenges/grammar/attached-pronouns'
    | '/challenges/grammar/case-system-overview'
    | '/challenges/grammar/colors'
    | '/challenges/grammar/definiteness-tanwin'
    | '/challenges/grammar/idafah'
    | '/challenges/grammar/independent-pronouns'
    | '/challenges/grammar/interrogatives-man-maa'
    | '/challenges/grammar/ism-ishaara-far'
    | '/challenges/grammar/ism-ishaara-near'
    | '/challenges/grammar/masculine-feminine'
    | '/challenges/grammar/mubtada-khabar'
    | '/challenges/grammar/prepositions'
    | '/challenges/grammar/yes-no-questions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arabic-with-mufti-saim/'
    | '/challenges/'
    | '/cognates/'
    | '/api/auth/$'
    | '/api/publish/$'
    | '/arabic-with-mufti-saim/lecture/$lectureId'
    | '/challenges/vocabulary/'
    | '/challenges/grammar/adjectives-agreement/'
    | '/challenges/grammar/attached-pronouns/'
    | '/challenges/grammar/case-system-overview/'
    | '/challenges/grammar/colors/'
    | '/challenges/grammar/definiteness-tanwin/'
    | '/challenges/grammar/idafah/'
    | '/challenges/grammar/independent-pronouns/'
    | '/challenges/grammar/interrogatives-man-maa/'
    | '/challenges/grammar/ism-ishaara-far/'
    | '/challenges/grammar/ism-ishaara-near/'
    | '/challenges/grammar/masculine-feminine/'
    | '/challenges/grammar/mubtada-khabar/'
    | '/challenges/grammar/prepositions/'
    | '/challenges/grammar/yes-no-questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArabicWithMuftiSaimIndexRoute: typeof ArabicWithMuftiSaimIndexRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  CognatesIndexRoute: typeof CognatesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublishSplatRoute: typeof ApiPublishSplatRoute
  ArabicWithMuftiSaimLectureLectureIdRoute: typeof ArabicWithMuftiSaimLectureLectureIdRoute
  ChallengesVocabularyIndexRoute: typeof ChallengesVocabularyIndexRoute
  ChallengesGrammarAdjectivesAgreementIndexRoute: typeof ChallengesGrammarAdjectivesAgreementIndexRoute
  ChallengesGrammarAttachedPronounsIndexRoute: typeof ChallengesGrammarAttachedPronounsIndexRoute
  ChallengesGrammarCaseSystemOverviewIndexRoute: typeof ChallengesGrammarCaseSystemOverviewIndexRoute
  ChallengesGrammarColorsIndexRoute: typeof ChallengesGrammarColorsIndexRoute
  ChallengesGrammarDefinitenessTanwinIndexRoute: typeof ChallengesGrammarDefinitenessTanwinIndexRoute
  ChallengesGrammarIdafahIndexRoute: typeof ChallengesGrammarIdafahIndexRoute
  ChallengesGrammarIndependentPronounsIndexRoute: typeof ChallengesGrammarIndependentPronounsIndexRoute
  ChallengesGrammarInterrogativesManMaaIndexRoute: typeof ChallengesGrammarInterrogativesManMaaIndexRoute
  ChallengesGrammarIsmIshaaraFarIndexRoute: typeof ChallengesGrammarIsmIshaaraFarIndexRoute
  ChallengesGrammarIsmIshaaraNearIndexRoute: typeof ChallengesGrammarIsmIshaaraNearIndexRoute
  ChallengesGrammarMasculineFeminineIndexRoute: typeof ChallengesGrammarMasculineFeminineIndexRoute
  ChallengesGrammarMubtadaKhabarIndexRoute: typeof ChallengesGrammarMubtadaKhabarIndexRoute
  ChallengesGrammarPrepositionsIndexRoute: typeof ChallengesGrammarPrepositionsIndexRoute
  ChallengesGrammarYesNoQuestionsIndexRoute: typeof ChallengesGrammarYesNoQuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognates/': {
      id: '/cognates/'
      path: '/cognates'
      fullPath: '/cognates/'
      preLoaderRoute: typeof CognatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic-with-mufti-saim/': {
      id: '/arabic-with-mufti-saim/'
      path: '/arabic-with-mufti-saim'
      fullPath: '/arabic-with-mufti-saim/'
      preLoaderRoute: typeof ArabicWithMuftiSaimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/vocabulary/': {
      id: '/challenges/vocabulary/'
      path: '/challenges/vocabulary'
      fullPath: '/challenges/vocabulary/'
      preLoaderRoute: typeof ChallengesVocabularyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic-with-mufti-saim/lecture/$lectureId': {
      id: '/arabic-with-mufti-saim/lecture/$lectureId'
      path: '/arabic-with-mufti-saim/lecture/$lectureId'
      fullPath: '/arabic-with-mufti-saim/lecture/$lectureId'
      preLoaderRoute: typeof ArabicWithMuftiSaimLectureLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish/$': {
      id: '/api/publish/$'
      path: '/api/publish/$'
      fullPath: '/api/publish/$'
      preLoaderRoute: typeof ApiPublishSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/yes-no-questions/': {
      id: '/challenges/grammar/yes-no-questions/'
      path: '/challenges/grammar/yes-no-questions'
      fullPath: '/challenges/grammar/yes-no-questions/'
      preLoaderRoute: typeof ChallengesGrammarYesNoQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/prepositions/': {
      id: '/challenges/grammar/prepositions/'
      path: '/challenges/grammar/prepositions'
      fullPath: '/challenges/grammar/prepositions/'
      preLoaderRoute: typeof ChallengesGrammarPrepositionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/mubtada-khabar/': {
      id: '/challenges/grammar/mubtada-khabar/'
      path: '/challenges/grammar/mubtada-khabar'
      fullPath: '/challenges/grammar/mubtada-khabar/'
      preLoaderRoute: typeof ChallengesGrammarMubtadaKhabarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/masculine-feminine/': {
      id: '/challenges/grammar/masculine-feminine/'
      path: '/challenges/grammar/masculine-feminine'
      fullPath: '/challenges/grammar/masculine-feminine/'
      preLoaderRoute: typeof ChallengesGrammarMasculineFeminineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/ism-ishaara-near/': {
      id: '/challenges/grammar/ism-ishaara-near/'
      path: '/challenges/grammar/ism-ishaara-near'
      fullPath: '/challenges/grammar/ism-ishaara-near/'
      preLoaderRoute: typeof ChallengesGrammarIsmIshaaraNearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/ism-ishaara-far/': {
      id: '/challenges/grammar/ism-ishaara-far/'
      path: '/challenges/grammar/ism-ishaara-far'
      fullPath: '/challenges/grammar/ism-ishaara-far/'
      preLoaderRoute: typeof ChallengesGrammarIsmIshaaraFarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/interrogatives-man-maa/': {
      id: '/challenges/grammar/interrogatives-man-maa/'
      path: '/challenges/grammar/interrogatives-man-maa'
      fullPath: '/challenges/grammar/interrogatives-man-maa/'
      preLoaderRoute: typeof ChallengesGrammarInterrogativesManMaaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/independent-pronouns/': {
      id: '/challenges/grammar/independent-pronouns/'
      path: '/challenges/grammar/independent-pronouns'
      fullPath: '/challenges/grammar/independent-pronouns/'
      preLoaderRoute: typeof ChallengesGrammarIndependentPronounsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/idafah/': {
      id: '/challenges/grammar/idafah/'
      path: '/challenges/grammar/idafah'
      fullPath: '/challenges/grammar/idafah/'
      preLoaderRoute: typeof ChallengesGrammarIdafahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/definiteness-tanwin/': {
      id: '/challenges/grammar/definiteness-tanwin/'
      path: '/challenges/grammar/definiteness-tanwin'
      fullPath: '/challenges/grammar/definiteness-tanwin/'
      preLoaderRoute: typeof ChallengesGrammarDefinitenessTanwinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/colors/': {
      id: '/challenges/grammar/colors/'
      path: '/challenges/grammar/colors'
      fullPath: '/challenges/grammar/colors/'
      preLoaderRoute: typeof ChallengesGrammarColorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/case-system-overview/': {
      id: '/challenges/grammar/case-system-overview/'
      path: '/challenges/grammar/case-system-overview'
      fullPath: '/challenges/grammar/case-system-overview/'
      preLoaderRoute: typeof ChallengesGrammarCaseSystemOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/attached-pronouns/': {
      id: '/challenges/grammar/attached-pronouns/'
      path: '/challenges/grammar/attached-pronouns'
      fullPath: '/challenges/grammar/attached-pronouns/'
      preLoaderRoute: typeof ChallengesGrammarAttachedPronounsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/grammar/adjectives-agreement/': {
      id: '/challenges/grammar/adjectives-agreement/'
      path: '/challenges/grammar/adjectives-agreement'
      fullPath: '/challenges/grammar/adjectives-agreement/'
      preLoaderRoute: typeof ChallengesGrammarAdjectivesAgreementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArabicWithMuftiSaimIndexRoute: ArabicWithMuftiSaimIndexRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  CognatesIndexRoute: CognatesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublishSplatRoute: ApiPublishSplatRoute,
  ArabicWithMuftiSaimLectureLectureIdRoute:
    ArabicWithMuftiSaimLectureLectureIdRoute,
  ChallengesVocabularyIndexRoute: ChallengesVocabularyIndexRoute,
  ChallengesGrammarAdjectivesAgreementIndexRoute:
    ChallengesGrammarAdjectivesAgreementIndexRoute,
  ChallengesGrammarAttachedPronounsIndexRoute:
    ChallengesGrammarAttachedPronounsIndexRoute,
  ChallengesGrammarCaseSystemOverviewIndexRoute:
    ChallengesGrammarCaseSystemOverviewIndexRoute,
  ChallengesGrammarColorsIndexRoute: ChallengesGrammarColorsIndexRoute,
  ChallengesGrammarDefinitenessTanwinIndexRoute:
    ChallengesGrammarDefinitenessTanwinIndexRoute,
  ChallengesGrammarIdafahIndexRoute: ChallengesGrammarIdafahIndexRoute,
  ChallengesGrammarIndependentPronounsIndexRoute:
    ChallengesGrammarIndependentPronounsIndexRoute,
  ChallengesGrammarInterrogativesManMaaIndexRoute:
    ChallengesGrammarInterrogativesManMaaIndexRoute,
  ChallengesGrammarIsmIshaaraFarIndexRoute:
    ChallengesGrammarIsmIshaaraFarIndexRoute,
  ChallengesGrammarIsmIshaaraNearIndexRoute:
    ChallengesGrammarIsmIshaaraNearIndexRoute,
  ChallengesGrammarMasculineFeminineIndexRoute:
    ChallengesGrammarMasculineFeminineIndexRoute,
  ChallengesGrammarMubtadaKhabarIndexRoute:
    ChallengesGrammarMubtadaKhabarIndexRoute,
  ChallengesGrammarPrepositionsIndexRoute:
    ChallengesGrammarPrepositionsIndexRoute,
  ChallengesGrammarYesNoQuestionsIndexRoute:
    ChallengesGrammarYesNoQuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
