/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CognatesIndexRouteImport } from './routes/cognates/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as ArabicWithMuftiSaimIndexRouteImport } from './routes/arabic-with-mufti-saim/index'
import { Route as ArabicWithMuftiSaimLectureLectureIdRouteImport } from './routes/arabic-with-mufti-saim/lecture.$lectureId'
import { Route as ApiPublishSplatRouteImport } from './routes/api/publish/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CognatesIndexRoute = CognatesIndexRouteImport.update({
  id: '/cognates/',
  path: '/cognates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArabicWithMuftiSaimIndexRoute =
  ArabicWithMuftiSaimIndexRouteImport.update({
    id: '/arabic-with-mufti-saim/',
    path: '/arabic-with-mufti-saim/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArabicWithMuftiSaimLectureLectureIdRoute =
  ArabicWithMuftiSaimLectureLectureIdRouteImport.update({
    id: '/arabic-with-mufti-saim/lecture/$lectureId',
    path: '/arabic-with-mufti-saim/lecture/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublishSplatRoute = ApiPublishSplatRouteImport.update({
  id: '/api/publish/$',
  path: '/api/publish/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arabic-with-mufti-saim/': typeof ArabicWithMuftiSaimIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/cognates/': typeof CognatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/publish/$': typeof ApiPublishSplatRoute
  '/arabic-with-mufti-saim/lecture/$lectureId': typeof ArabicWithMuftiSaimLectureLectureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arabic-with-mufti-saim': typeof ArabicWithMuftiSaimIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/cognates': typeof CognatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/publish/$': typeof ApiPublishSplatRoute
  '/arabic-with-mufti-saim/lecture/$lectureId': typeof ArabicWithMuftiSaimLectureLectureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arabic-with-mufti-saim/': typeof ArabicWithMuftiSaimIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/cognates/': typeof CognatesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/publish/$': typeof ApiPublishSplatRoute
  '/arabic-with-mufti-saim/lecture/$lectureId': typeof ArabicWithMuftiSaimLectureLectureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arabic-with-mufti-saim/'
    | '/challenges/'
    | '/cognates/'
    | '/api/auth/$'
    | '/api/publish/$'
    | '/arabic-with-mufti-saim/lecture/$lectureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arabic-with-mufti-saim'
    | '/challenges'
    | '/cognates'
    | '/api/auth/$'
    | '/api/publish/$'
    | '/arabic-with-mufti-saim/lecture/$lectureId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arabic-with-mufti-saim/'
    | '/challenges/'
    | '/cognates/'
    | '/api/auth/$'
    | '/api/publish/$'
    | '/arabic-with-mufti-saim/lecture/$lectureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArabicWithMuftiSaimIndexRoute: typeof ArabicWithMuftiSaimIndexRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  CognatesIndexRoute: typeof CognatesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublishSplatRoute: typeof ApiPublishSplatRoute
  ArabicWithMuftiSaimLectureLectureIdRoute: typeof ArabicWithMuftiSaimLectureLectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognates/': {
      id: '/cognates/'
      path: '/cognates'
      fullPath: '/cognates/'
      preLoaderRoute: typeof CognatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic-with-mufti-saim/': {
      id: '/arabic-with-mufti-saim/'
      path: '/arabic-with-mufti-saim'
      fullPath: '/arabic-with-mufti-saim/'
      preLoaderRoute: typeof ArabicWithMuftiSaimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic-with-mufti-saim/lecture/$lectureId': {
      id: '/arabic-with-mufti-saim/lecture/$lectureId'
      path: '/arabic-with-mufti-saim/lecture/$lectureId'
      fullPath: '/arabic-with-mufti-saim/lecture/$lectureId'
      preLoaderRoute: typeof ArabicWithMuftiSaimLectureLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish/$': {
      id: '/api/publish/$'
      path: '/api/publish/$'
      fullPath: '/api/publish/$'
      preLoaderRoute: typeof ApiPublishSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArabicWithMuftiSaimIndexRoute: ArabicWithMuftiSaimIndexRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  CognatesIndexRoute: CognatesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublishSplatRoute: ApiPublishSplatRoute,
  ArabicWithMuftiSaimLectureLectureIdRoute:
    ArabicWithMuftiSaimLectureLectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
